# Numpy

In [4]:
import numpy as np
arr = np.array([10,20,30])
print(arr)

[10 20 30]


In [5]:
#0-D Arrays

arr = np.array(42)
print(arr)

42


In [7]:
#1-D Arrays

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [17]:
#2-D Arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [16]:
#3-D Arrays

arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


# Higher Dimensional Arrays

In [18]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


# Accessing

In [23]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [24]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('5th element on 2nd row:', arr[1,4])

5th element on 2nd row: 10


In [25]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


# Negative Indexing

In [27]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim:', arr[1,-1])

Last element from 2nd dim: 10
